#!/bin/bash
# 
# xmonad "startup hook" script. This gets run after xmonad is initialized,
# via the startupHook facility provided by xmonad. It's useful for 
# running any programs which you want to use within xmonad but
# which don't need to be initialized before xmonad is running. 
#
# Author: David Brewer
# Repository: https://github.com/davidbrewer/xmonad-ubuntu-conf

#
# TRAY ICON SOFTWARE
#

# Empathy chat client (-h: start hidden, -n: don't connect on launch)
#if [ -z "$(pgrep empathy)" ] ; then
    #empathy -h -n &
#fi

# Remmina remote desktop connection client (-i: start hidden)
#if [ -z "$(pgrep remmina)" ] ; then
    #remmina -i &
#fi

# Network manager, so we don't have to configure wifi at the command line.
if [ -z "$(pgrep nm-applet)" ] ; then
    nm-applet --sm-disable &
fi

# Applet for managing print jobs from the tray.
if [ -z "$(pgrep system-config-printer-applet)" ] ; then
    system-config-printer-applet &
fi

#
# APPLICATION LAUNCHER
#

# Use synapse as our app launcher. (-s: don't display until requested) 
if [ -z "$(pgrep kupfer)" ] ; then
    kupfer --no-splash &
fi

# execute nautilus for background etc (-n: hidden) 
#if [ -z "$(pgrep nautilus)" ] ; then
    #nautilus -n &
#fi
# execute clipboard manager
if [ -z "$(pgrep parcellite)" ] ; then
    parcellite &
fi

# execute night mode eye saver redshift
if [ -z "$(pgrep redshift)" ] ; then
    #redshift -l 41.423824:2.148811 & #Barcelona
    redshift -l -16.6395265:-49.2312328  & #Goiania
fi

if [ -z "$(pgrep btsync-gui)" ] ; then
    btsync-gui &
fi

if [ -z "$(pgrep dropbox)" ] ; then
    dropbox &
fi

if [ -z "$(pgrep nm-applet)" ] ; then
    nm-applet &
fi

#if [ -z "$(pgrep variety)" ] ; then
    #variety &
#fi

if [ -z "$(pgrep xautolock)" ] ; then
    xautolock -time 30 -locker 'sudo dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 "org.freedesktop.login1.Manager.Suspend" boolean:true'  -notify 30 -notifier "notify-send -t 5000 -i gtk-dialog-info 'Locking in 10 seconds'"
fi

